<?php
namespace PHPMyPlex;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-04-26 at 22:09:55.
 */
class MyPlexTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var MyPlex
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new MyPlex;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers PHPMyPlex\MyPlex::getServers
     * @todo   Implement testGetServers().
     */
    public function testGetServers()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPMyPlex\MyPlex::__get
     * @todo   Implement test__get().
     */
    public function test__get()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
